name: Publish Github Pages

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.71.1'
          extended: true

      - name: Build
        run: hugo

      - name: Commit files
        # if: ${{ github.repository == 'X-lab2017/xlab-website' && github.ref == 'refs/heads/master' }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git clone https://github.com/X-lab2017/X-lab2017.github.io.git public_temp.git
          mv public_temp.git/.git public/.git
          cd ./public
          git add .
          git commit -m "${{ github.event.head_commit.message }}"
          cd ..

      - name: Test git status
        env: 
          GitClean: ${{ echo git status -s }}
        run: |
          echo 123
          echo env.GitClean
          echo 123

      - name: Deploy
        if: ${{ env.GitClean == '' }}
        run: |
          echo 123
          echo env.GitClean
          echo 123

      # - name: Push changes to X-lab2017.github.io
      #   if: ${{ github.repository == 'X-lab2017/xlab-website' && github.ref == 'refs/heads/master' }}
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.TARGET_REPO_GITHUB_TOKEN }}
      #     branch: master
      #     force: true
      #     tags: false
      #     directory: ./public
      #     repository: X-lab2017/X-lab2017.github.io
